export const ADD_MAIN_PLAYER = 'ADD_MAIN_PLAYER';
export const ADD_SECONDARY_PLAYER = 'ADD_SECONDARY_PLAYER';
export const REMOVE_MAIN_PLAYER = 'REMOVE_MAIN_PLAYER';
export const REMOVE_SECONDARY_PLAYER = 'REMOVE_SECONDARY_PLAYER';
